# Generated by Django 3.0.3 on 2020-02-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=200, verbose_name='Session_key')),
                ('image', models.ImageField(upload_to='media/', verbose_name='image')),
            ],
        ),
    ]
