# Generated by Django 3.0.3 on 2020-02-15 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0003_auto_20200215_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteuser',
            name='session_key',
        ),
    ]
