# Generated by Django 3.0.3 on 2020-02-15 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0005_siteuser_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='session_key',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='session_key'),
        ),
    ]
