# Generated by Django 3.0.3 on 2020-02-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desktop', '0006_auto_20200215_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteuser',
            name='session_key',
            field=models.CharField(default=0, max_length=200, verbose_name='session_key'),
            preserve_default=False,
        ),
    ]
